---

- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Fail if alerta secretkey not defined
  fail:
    msg: alerta_secretkey must be defined if you enable alerta authentification
  when: alerta_auth_required | bool and not alerta_secretkey

- name: Define alerta_pip_packages
  set_fact:
    alerta_pip_packages: '{{ alerta_pip_base_packages +
                             alerta_pip_depend_packages +
                             alerta_pip_plugins_packages }}'

- import_tasks: install.yml

- import_tasks: configure.yml

- import_tasks: web-console.yml

- name: Start & enable Alerta
  systemd:
    name: alerta
    state: started
    enabled: true
    daemon_reload: true
